# Generated by Django 5.0 on 2023-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
