# Generated by Django 5.0 on 2023-12-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_alter_appointmentmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
