# Generated by Django 5.0 on 2023-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_alter_appointmentmodel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='time',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
