# Generated by Django 5.0 on 2023-12-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_remove_appointmentmodel_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='datetime',
            new_name='from_datetime',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='to_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
